import { SMenu, SCard, SHeader, SIcon, SButton, STip, STag } from "@surrealism/index.slint";
import { UseIcons } from "@surrealism/use/index.slint";

import { FilesystemExplorer } from "./file-explorer.slint";
import { TableViewPage } from "./table_view_page.slint";
import { CustomTableViewPage } from "./custom-table.slint";
import { HomeForm } from "home.slint";

export component App inherits Window {
    height: 600px;
    width: 800px;

    in-out property <string> window-title: "Anclient.slint";
    title: window-title;

    private property <int> router-index : 0;

    out property <length> web_x;
    out property <length> web_y;
    out property <length> web_width;
    out property <length> web_height;

    in-out property <string> webview-status: "Webview not started";
    in-out property <string> syncing-status: "Ready";

    callback menu-changed(int, string, string);
    callback item_clicked(string, bool);
    callback pingws();

    public function update-syncing-status(status: string) {
        syncing-status = status;
        if (root.router-index == 0) {
            index-page.ws-status = status; 
        }
    }

    HorizontalLayout {
      left-wrapper:=Rectangle {
        z: 111;
        height: 100%;
        width: menu.width;
        clip: false;
        menu:=SMenu {
          menu-data:[
            {id:"0",icon:UseIcons.icons.FileCode,name:"Code"},
            {id:"1",icon:UseIcons.icons.Search,name:"Search"},
            {id:"2",icon:UseIcons.icons.Folder,name:"Help"},
            {id:"3",icon:UseIcons.icons.Help,name:"Help"},
          ];

          change(index, data) => {
            debug(index, data);
            router-index = index;
            menu-changed(index, data.id, data.name);
          }
        }
      }

      right-wrapper:=Rectangle {
        z: 100;
        width: parent.width - menu.width;
        background: #2b2b32;
        VerticalLayout {
          width: parent.width;
          height: parent.height;

          index-page := HomeForm { 
            width: 100%;
            height: root.router-index == 0 ? parent.height - 14pt : 0pt;
            visible: root.router-index == 0;
            pingws-clicked => { root.pingws(); }
          }

          if (router-index == 1) : webview_slot := Rectangle {
            background: #e0e0e0;
            Text { text: "Page 2"; }
          }

          if (router-index == 2) : Rectangle {
            background: #b0d0d0;
            // Uncomment the following line to reproduce slint compiler bug.
            // FilesystemExplorer { width: 100%; height: 100%; }
            CustomTableViewPage { width: 100%; height: 100%; }
          }

          if (router-index == 3) : Rectangle {
            background: #b0d0d0;
            TableViewPage { width: 100%; height: 100%; }
          }

          status-bar:= HorizontalLayout {
            padding-top: 1pt;
            padding-left: 12pt;
            STag{ text: root.syncing_status; }
          }
        }
      }
    }

    popup:=STip {
      text: "Credits to: SurrealismUI";
      position: Bottom;
    }
}
