import { HorizontalBox, StandardTableView, ScrollView, GroupBox, StyleMetrics, LineEdit } from "std-widgets.slint";
import { SCheckbox } from "@surrealism/index.slint";
import { SButton } from "../../surrealism-0.5.3/index.slint";

export struct PathItemData {
    is_folder: bool,
    indent   : [string], // [+, |, T, L, -]
    fname    : string,
    size     : string,
    type     : string,
    fullpath : string,
    iselected: bool
}

export component FileTable {
    width: 600px;
    height: 400px;
    
    property <int> sort-index: -1;
    property <bool> sort-ascending;

    in-out property <string> current_path;

    in-out property <[PathItemData]> row_data: [
        {is_folder: false, indent: [], fname: "test",   type: "test-type", size: "0", fullpath: "~/x/y.z", iselected: false},
        {is_folder: true,  indent: [], fname: "folder", type: "folder",    size: "",  fullpath: "~/x/dir", iselected: false}
    ];

    callback row-selected(PathItemData);
    callback row-double-click(PathItemData);
    callback upload();

    pure callback filter_sort_model([PathItemData], string, int, bool) -> [PathItemData];
    filter_sort_model(row-data, filter, sort-index, sort-ascending) => { 
        return row-data; 
    }

    function icons(idx: string) -> image {
        if ("d" == idx) {
            return @image-url("@surrealism/icons/folder-open.svg");
        }
        if ("|" == idx) {
            return @image-url("@surrealism/icons/right.svg");
        }
        if ("e" == idx) {
            return @image-url("@surrealism/icons/link-left.svg");
        }
        return @image-url("@surrealism/icons/more.svg");
    }

    HorizontalBox {
      vertical-stretch: 1;

      VerticalLayout {
        Text { text: root.current_path; }

        // Table Header
        HorizontalLayout {
            padding: 8px;
            Text { text: @tr("Name"); width: 30%; color: #bbb; font-weight: 700; }
            Text { text: @tr("Type"); width: 35%; color: #bbb; font-weight: 700; }
            Text { text: @tr("Size"); width: 35%; color: #bbb; font-weight: 700; }
        }

        // Table Body Rows
        ScrollView {
          VerticalLayout {
            for row in root.filter_sort_model(root.row_data, filter-edit.text, root.sort-index, root.sort-ascending) : Rectangle {
                init => {
                    debug(row.iselected ? "ON" : "OFF", row.fullpath);
                }

                background: row.iselected ? rgba(0, 120, 215, 0.2) : rgba(0, 0, 0, 0.02);
                height: 24pt;
                touchbox := TouchArea {
                    clicked => {
                        debug("TouchArea.cliced()");
                        row.iselected = !row.iselected;
                        chkbox.actived = row.iselected;
                        root.row_selected(row);
                    }
                    double-clicked => { root.row_double_click(row); }
                    
                    Rectangle {
                        background: parent.has-hover ? rgba(0.2, 0.2, 0.2, 0.08) : transparent;
                        animate background { duration: 150ms; }
                    }
                }

                HorizontalLayout {
                    padding: 8px;
                    HorizontalLayout {
                        width: 30%; height: parent.height;
                        padding-top: 6pt;
                        padding-bottom: 6pt;
                        for icon in row.indent : Image {
                            source: root.icons(icon);
                            width: 12pt;
                            height: 12pt;
                        }

                        chkbox := SCheckbox {
                            text: "";
                            actived: row.iselected;
                            disabled: row.is_folder;
                            height: 22pt; width: 22pt;
                            clicked(text, value, actived) => {
                                touchbox.clicked();
                            }
                        }

                        if (row.is-folder) : Image {
                            // horizontal-alignment: ImageHorizontalAlignment.left;
                            source: root.icons("d");
                            width: 14pt; height: 14pt;
                        }
                        if (!row.is-folder): Image {
                            // horizontal-alignment: ImageHorizontalAlignment.left;
                            source: root.icons("e");
                            width: 14pt; height: 14pt;
                        }
                        Text {
                            color: #e5ffff;
                            text: row.fname;
                            font-weight: 700;
                            horizontal-stretch: 1;
                            overflow: elide;
                        }
                    }

                    Text { width: 35%; color: #ccc; text: row.type; vertical-alignment: center; }
                    Text { width: 35%; color: #ccc; text: row.size; vertical-alignment: center; }
                }
            }
          }
        }

        HorizontalLayout {
            // Text { text: @tr("Filter by Name:"); }
            filter-edit := LineEdit {
                placeholder-text: @tr("Enter filter text");
            }

            SButton {
                text: @tr("Upload");
                clicked => { root.upload(); }
            }
        }
      }
    }
}