import { HorizontalBox, StandardTableView, ScrollView, GroupBox, StyleMetrics, LineEdit } from "std-widgets.slint";

export struct PathItemData {
    is_folder: bool,
    indent   : [string], // [+, |, T, L, -]
    fname    : string,
    size     : string,
    type     : string,
    fullpath : string
}

export component FileTable {
    width: 600px;
    height: 400px;
    
    property <int> sort-index: -1;
    property <bool> sort-ascending;

    // in-out property <[[StandardListViewItem]]> row_data: [];
    in-out property <[PathItemData]> row_data: [];

    callback row-selected(PathItemData);

    pure callback filter_sort_model([PathItemData], string, int, bool) -> [PathItemData];
    filter_sort_model(row-data, filter, sort-index, sort-ascending) => { 
        return row-data; 
    }

    function icons(idx: string) -> image {
        return @image-url("");
    }

    HorizontalBox {
        vertical-stretch: 1;
        GroupBox {
            title: "Custom Table View with Icons";

            VerticalLayout {
                // Table Header
                HorizontalLayout {
                    padding: 8px;
                    Text { text: "Icon / Col 1"; width: 30%; font-weight: 700; }
                    Text { text: "Header 2"; width: 35%; font-weight: 700; }
                    Text { text: "Header 3"; width: 35%; font-weight: 700; }
                }

                // Table Body Rows
                ScrollView {
                    VerticalLayout {
                        for row in root.filter_sort_model(root.row_data, filter-edit.text, root.sort-index, root.sort-ascending) : Rectangle {
                            background: rgba(0, 0, 0, 0.02);
                            height: 40px;
                            TouchArea {
                                clicked => {
                                    root.row_selected(row);
                                }
                                
                                // Optional visual feedback: changes background color on hover
                                Rectangle {
                                    background: parent.has-hover ? rgba(0, 0, 0, 0.08) : transparent;
                                    animate background { duration: 150ms; }
                                }
                            }

                            HorizontalLayout {
                                padding: 8px;
                                // vertical-alignment: center;

                                // Column 1: Renders the SVG if present
                                HorizontalLayout {
                                    width: 30%;
                                    spacing: 8px;
                                    for icon in row.indent : Image {
                                        source: root.icons(icon);
                                        width: 32px;
                                        height: 32px;
                                    }
                                    if (!row.is-folder) : Image {
                                        source: root.icons("d");
                                    }
                                    Text { text: row.fname; }
                                }

                                // Column 2
                                Text { width: 35%; text: row.type; vertical-alignment: center; }

                                // Column 3
                                Text { width: 35%; text: row.size; vertical-alignment: center; }
                            }
                        }
                    }
                }

                VerticalLayout {
                    Text { text: @tr("Filter by Name:"); }
                    filter-edit := LineEdit {
                        placeholder-text: @tr("Enter filter text");
                    }
                }
            }
        }
    }
}