import { SMenu, SCard, SHeader, SIcon, SButton, STip, STag, SPopup } from "@surrealism/index.slint";
import { UseIcons } from "@surrealism/use/index.slint";
import { LineEdit } from "std-widgets.slint";

export component GUIClientSettings {

    in-out property <[string]> file_paths;

    callback pingws-clicked();
    callback echows-clicked(string);

    Rectangle {
        height: 100%;
        width: 100%;
        vertical-stretch: 1;
        VerticalLayout {
          HorizontalLayout {
            alignment: center;
            SCard {
                card-width: 48px;
                card-height: 48px;
                SIcon {
                    height: parent.height;
                    width: parent.width;
                    source: @image-url("imgs/album.svg");
                }
            }
          }

        //   f1 := LineEdit { text: "~/github/anclient/examples/example.slint/rst/docsreq.ast.json"; }
        //   f2 := LineEdit { text: "~/github/anclient/examples/example.slint/rst/docsresp.ast.json"; }
          // f0 := LineEdit { text: file_paths[0]; }
          // f1 := LineEdit { text: file_paths[1]; }
          SButton {
            text: "Ping Task Placing";
            width: 100%;
            padding: 8pt;
            clicked => {
              file_paths = ["~/github/anclient/examples/ EXAMPLE.SLINT/RST/DOCSREQ.AST.JSON",
                            "~/GITHUB/ANCLIENT/EXAMPLES/ example.slint/rst/docsresp.ast.json"];
              pingws-clicked();
            }
          }

          HorizontalLayout {
            padding: 24px;
            alignment: space-around;
            vertical-stretch: 1;

            msg-edit:=LineEdit {
                width: 85%;
                placeholder-text: @tr("Echo by Album Client");
            }
            SButton {
                show-icon: true;
                icon: UseIcons.icons.Smiling-face;
                theme: Primary;
                text: "Echo to IPC Agent";
                clicked => {
                    echows-clicked(msg-edit.text);
                }
            }
          }

          HorizontalLayout {
            vertical-stretch: 50%;
          }
        }
    }
}