import { SMenu, SCard, SHeader, SIcon, SButton, STip, STag } from "@surrealism/index.slint";
import { UseIcons } from "@surrealism/use/index.slint";

// import { TreeData } from "./file-tree.slint";
import { FilesystemExplorer } from "./file-explorer.slint";
import { TableViewPage } from "./table_view_page.slint";
import { CustomTableViewPage } from "./custom-table.slint";


export component HomeForm {
    Rectangle {
        height: 100%; width: 100%;
        VerticalLayout {
          HorizontalLayout {
            padding: 8px;
            alignment: center;
            Rectangle {
                height:header.height ;
                width: parent.width - 16px;
                header:=SHeader {
                value: [{label:"SurrealismUI",value:"1"},{label:"menu:Index",value:"2"}];
                }
            }
          }
          HorizontalLayout {
            padding: 24px;
            alignment: space-around;
            STag {
                theme: Warning;
                text: "SurrealismUI V0.5.3";
            }
            STag {
                theme: Success;
                text: "MIT License";
            }
            STag {
                theme: Error;
                text: "Slint for CMake!";
            }
            STag {
                theme: Error;
                text: "Credit to: syf20020816@outlook.com";
            }
          }
          HorizontalLayout {
            alignment: center;
            SCard {
                card-width: 460px;
                card-height: 320px;
                SIcon {
                height: parent.height;
                width: parent.width;
                source: @image-url("imgs/album.svg");
                }
            }
          }
          HorizontalLayout {
            padding: 24px;
            alignment: space-around;
            SButton {
                text: "Try SurrealismUI";
                clicked => {
                // popup.success("Try SurrealismUI!!! Let's GO!");
                }
            }

            SButton {
                show-icon: true;
                icon: UseIcons.icons.Smiling-face;
                theme: Primary;
                text: "Star on Github!";
            }
            STip {
                text: "GO TO SurrealismUI WIKI?\n Click here!";
                height: wiki-btn.height;
                width: wiki-btn.width;
                position: Bottom;
                wiki-btn:=SButton {
                theme: Success;
                text: "Read Wiki!~~~";
                clicked => {
                    parent.clicked();
                }
                }
            }
          }
        }
    }
}