import { SMenu, SCard, SHeader, SIcon, SButton, STip, STag, SPopup } from "@surrealism/index.slint";
import { UseIcons } from "@surrealism/use/index.slint";

import { TableViewPage } from "./table_view_page.slint";
import { CustomTableViewPage } from "./custom-table.slint";


export component HomeForm {

    in-out property <string> ws-status: "Ready";
    callback pingws-clicked();

    Rectangle {
        height: 100%; width: 100%;
        VerticalLayout {
          HorizontalLayout {
            padding: 8px;
            alignment: center;
            Rectangle {
                height:header.height ;
                width: parent.width - 16px;
                header:=SHeader {
                value: [{label:"SurrealismUI", value:"1"}, {label:"menu:Index", value:"2"}];
                }
            }
          }
          HorizontalLayout {
            padding: 24px;
            alignment: space-around;
            STag {
                theme: Warning;
                text: "Warning";
            }
            STag {
                theme: Success;
                text: "Success";
            }
            STag {
                theme: Error;
                text: "Error";
            }
            STag {
                theme: Info;
                text: "Credit to: syf20020816@outlook.com";
            }
          }
          HorizontalLayout {
            alignment: center;
            SCard {
                card-width: 460px;
                card-height: 320px;
                SIcon {
                height: parent.height;
                width: parent.width;
                source: @image-url("imgs/album.svg");
                }
            }
          }
          HorizontalLayout {
            padding: 24px;
            alignment: space-around;
            SButton {
                text: "Ping IPC Agent";
                clicked => {
                    pingws-clicked();
                }
            }

            SButton {
                show-icon: true;
                icon: UseIcons.icons.Smiling-face;
                theme: Primary;
                text: "Star on Github!";
                clicked => {
                    popup.open();
                }
            }
            STip {
                text: "GO TO SurrealismUI WIKI?\n Click here!";
                height: wiki-btn.height;
                width: wiki-btn.width;
                position: Bottom;
                wiki-btn:=SButton {
                    theme: Success;
                    text: "Read Wiki ...";
                    clicked => {
                        parent.clicked();
                    }
                }
            }
          }
        }

        popup := SPopup {
            background: #d5f371;
            VerticalLayout {
                padding: 12px;
                alignment: center;
                Text{ horizontal-alignment: center; font-size: 24pt; text: root.ws-status; }
                Text{ horizontal-alignment: center; font-size: 16pt; color: #223623;
                      text: "Click to close this popup.";}
            }
        }
    }
}