export struct UserDialogModel {
    title: string,
    detail: string,
    icon: string,

    has-cancel: bool,
    has-abort : bool,
}

export struct UserProfileModel {
    info_label: string,
    detail_label: string,

    org_name: string,
    market_name: string,
    regiserv: string,

    orgs_list: [string],
    org_selected: string,
    domains_list: [string],
    domain_selected: string,
    domain_selected_idx: int,
    synodes_list: [string],
    jserv_list  : [string],
    synode_selected: string,
    synode_selected_idx: int,

    synode_jserv: string,
    user_id_text: string,
    password_text: string,
    confirm_password_text: string,

    device: string,
    is_device_locked: bool,

    qr_code_image: image,
    show_qr_code: bool,
}

export enum SyncingIcon { invisible, pushing, publish, private, /** TODO Synchronized to local synode? */localonly }

export struct PathItemData {
    is_folder: bool,
    indent   : [string], // [+, |, T, L, -]
    fname    : string,
    size     : string,
    type     : string,
    fullpath : string,
    iselected: bool,
    syncicon : SyncingIcon
}

export struct AppModel {
    window_title: string,
    menu_id: string,
    dlg_type: int,

    webview_status: string,
    syncing_status: [string],

    current_pth: string,
    filelist: [PathItemData],
    path_crumbs: [PathItemData], // current_pth segments
    enable_vol: bool,
    synode_linked: bool,
}
