xcopy /y /i "xvExporter.addin" "%ALLUSERSPROFILE%\Autodesk\Revit\Addins\2017\"
xcopy /y /i "assets\*.*" "%ALLUSERSPROFILE%\Autodesk\Revit\Addins\2017\xvExporter\assets\"
xcopy /y /i "bin\Debug\gltf-export*" "%ALLUSERSPROFILE%\Autodesk\Revit\Addins\2017\xvExporter"
xcopy /y /i "bin\Debug\glTF*" "%ALLUSERSPROFILE%\Autodesk\Revit\Addins\2017\xvExporter"
xcopy /y /i "bin\Debug\Newtonsoft*" "%ALLUSERSPROFILE%\Autodesk\Revit\Addins\2017\xvExporter"