FROM nginx
COPY example.js/react-quiz/dist/* /usr/share/nginx/html/react-quiz/
COPY example.js/x-visual/bar-chart/* /usr/share/nginx/html/x-visual/bar-chart/
COPY example.cs/file.upload/Anclient.upload-0.3.zip /usr/share/nginx/html/downloads/
COPY index.html /usr/share/nginx/html/
